# Conda environment for Data Science in Azure
# Platform: Linux
# First Time Use:
#   $ conda env create --file ./environments/conda.lock.yml
# Use:
#   $ conda activate conda
# Creation for the record in Windows:
#   $ conda info --envs
#   $ conda env remove -n conda
#   $ conda env create --file ./environments/conda.yml 
#   $ conda activate conda
#   $ conda env export > ./environments/conda.lock.yml
name: conda
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - pyodbc
  - snowflake-connector-python
  - flask
  - flask-sqlalchemy
  - flask-login
  - pip:
    - datetime
    - python-dotenv
    - pathlib
    - argparse
    - requests
    - catboost 
    - azure-ai-ml
    - azure-keyvault-secrets
    - azure-identity
    - azure-devops
    - mlflow
    - ipykernel
    - yfinance
    - openai
    - nltk







